# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Beleg's Blog
email: melkorbane@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    Some resume/cv stuff will be uploaded here, along with some personal and contact information, probably thoughts, reflections, ideas, comments or any other public statements by the author.
    There will be a name too. However, if you are reading this and do not know the author, you probably got no business here.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://errand.ir/jekyll-test" # the base hostname & protocol for your site
baseurl: "/jekyll-test"
twitter_username: b_cuthalion
github_username:  BelegCuthalion

# Build settings
markdown: kramdown

theme: jekyll-theme-leap-day
